# Generated by Django 3.2.10 on 2021-12-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_interface', '0013_auto_20211231_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_interface.interface')),
            ],
        ),
    ]
