# Generated by Django 3.2.10 on 2022-01-09 11:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_interface', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(default=None, max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('findings', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('review_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('DONE', 'Done')], default='REQUESTED', max_length=15)),
                ('interface', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_interface.interface')),
                ('requestor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestor', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
