# Generated by Django 3.2.10 on 2022-01-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_name',
        ),
    ]
