# Generated by Django 3.2.10 on 2022-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_review', '0002_auto_20220109_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='findings',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('DONE', 'DONE')], default='OPEN', max_length=15),
        ),
    ]
