# Generated by Django 3.2.10 on 2022-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_review', '0002_remove_review_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
