# Generated by Django 3.2.10 on 2022-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default='', max_length=10, verbose_name='APP-ID')),
                ('short_name', models.CharField(default='', max_length=20)),
                ('mail_address', models.EmailField(default='', max_length=60)),
            ],
        ),
    ]
