# Generated by Django 3.2.10 on 2022-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='mail_address',
            field=models.EmailField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
