# Generated by Django 3.2.10 on 2022-01-09 11:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_id', models.CharField(default='', max_length=10, verbose_name='Interface ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(default='', max_length=500)),
                ('owned_interface', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('production_start_at', models.DateField(default=datetime.date.today)),
                ('decommissioning_at', models.DateField(blank=True, default=None, null=True)),
                ('multi_provider', models.BooleanField(default=False)),
                ('contract_description', models.URLField(blank=True, default=None, null=True, verbose_name='Interface Contract URL')),
                ('restriction', models.BooleanField(default=False)),
                ('restriction_text', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('restriction_code', models.CharField(blank=True, choices=[('NUTZUNG', 'NUTZUNG'), ('TEST', 'TEST')], default=None, max_length=20, null=True)),
                ('status', models.CharField(choices=[('EINGANG', 'Eingang'), ('ENTWICKLUNG', 'Entwicklung'), ('TEST', 'Test'), ('PRODUKTION', 'Produktion'), ('RUECKZUG', 'Rueckzug'), ('HISTORISCH', 'Historisch'), ('ABGELEHNT', 'Abgelehnt')], default='EINGANG', max_length=32)),
                ('model_origin', models.CharField(choices=[('CODE', 'Code'), ('CONTRACT', 'Contract'), ('MODEL', 'Model')], default='CODE', max_length=10)),
                ('info_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIONAL', 'Confidentional'), ('SECRET', 'Secret')], default='INTERNAL', max_length=20)),
                ('infoflow_direction', models.CharField(choices=[('TO_PROVIDER', 'To Provider'), ('FROM_PROVIDER', 'From Provider'), ('BOTH_DIRECTIONS', 'Both Directions')], default='BOTH_DIRECTIONS', max_length=20)),
                ('accessibility', models.CharField(choices=[('DOMAIN_INTERNAL', 'Domain internal'), ('CROSS_DOMAIN', 'Cross domain')], default='DOMAIN_INTERNAL', max_length=20)),
                ('communication_pattern', models.CharField(choices=[('REQUEST_REPLY', 'Request-Reply'), ('FIRE_FORGET', 'Fire-Forget')], default='REQUEST_REPLY', max_length=20)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner_application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app_application.application')),
            ],
        ),
    ]
