# Generated by Django 3.2.10 on 2022-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='interface_type',
            field=models.CharField(choices=[('API', 'API'), ('WEB_SERVICE', 'SOAP Web Service'), ('QUEUE', 'Queue'), ('FILE_TRANSFER', 'File Transfer')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='production_start_at',
            field=models.DateField(default=None),
        ),
    ]
