# Generated by Django 3.2.10 on 2021-12-27 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterfaceList',
            new_name='Interface',
        ),
    ]
