# Generated by Django 3.2.10 on 2022-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0002_auto_20220110_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_id',
            field=models.CharField(default='will be assigned automatically', max_length=31, verbose_name='Interface ID'),
        ),
    ]
