# Generated by Django 3.2.10 on 2021-12-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0002_rename_interfacelist_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='interface',
            new_name='name',
        ),
    ]
