# Generated by Django 3.2.10 on 2021-12-27 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0003_rename_interface_interface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='business_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='interface',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='interface',
            name='decommissioning_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='interface',
            name='info_classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIONAL', 'Confidentional'), ('SECRET', 'Secret')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='interface',
            name='infoflow_direction',
            field=models.CharField(choices=[('BOTH_DIRECTIONS', 'Both Directions'), ('TO_PROVIDER', 'To Provider'), ('FROM_PROVIDER', 'From Provider')], default='BOTH_DIRECTIONS', max_length=20),
        ),
        migrations.AddField(
            model_name='interface',
            name='is_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='model_origin',
            field=models.CharField(choices=[('CODE', 'Code'), ('CONTRACT', 'Contract'), ('MODEL', 'Model')], default='CODE', max_length=10),
        ),
        migrations.AddField(
            model_name='interface',
            name='production_start_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='interface',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('EINGANG', 'Eingang'), ('ENTWICKLUNG', 'Entwicklung'), ('TEST', 'Test'), ('PRODUKTION', 'Produktion'), ('RUECKZUG', 'Rueckzug'), ('HISTORISCH', 'Historisch'), ('ABGELEHNT', 'Abgelehnt')], default='EINGANG', max_length=16),
        ),
    ]
