# Generated by Django 3.2.10 on 2022-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0003_alter_interface_interface_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='accessibility',
            field=models.CharField(choices=[('DOMAIN_INTERNAL', 'Domain internal'), ('CROSS_DOMAIN', 'Cross domain')], default=('DOMAIN_INTERNAL', 'Domain internal'), max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='communication_pattern',
            field=models.CharField(choices=[('REQUEST_REPLY', 'Request-Reply'), ('FIRE_FORGET', 'Fire-Forget')], default=('REQUEST_REPLY', 'Request-Reply'), max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='info_classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIONAL', 'Confidentional'), ('SECRET', 'Secret')], default=('INTERNAL', 'Internal'), max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='infoflow_direction',
            field=models.CharField(choices=[('TO_PROVIDER', 'To Provider'), ('FROM_PROVIDER', 'From Provider'), ('BOTH_DIRECTIONS', 'Both Directions')], default=('BOTH_DIRECTIONS', 'Both Directions'), max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='model_origin',
            field=models.CharField(choices=[('CODE', 'Code'), ('CONTRACT', 'Contract'), ('MODEL', 'Model')], default=('CODE', 'Code'), max_length=10),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('EINGANG', 'Eingang'), ('ENTWICKLUNG', 'Entwicklung'), ('TEST', 'Test'), ('PRODUKTION', 'Produktion'), ('RUECKZUG', 'Rueckzug'), ('HISTORISCH', 'Historisch'), ('ABGELEHNT', 'Abgelehnt')], default=('EINGANG', 'Eingang'), max_length=32),
        ),
    ]
