# Generated by Django 3.2.10 on 2021-12-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0004_auto_20211227_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='business_id',
        ),
        migrations.AddField(
            model_name='interface',
            name='interface_id',
            field=models.CharField(default='', max_length=10, verbose_name='Interface ID'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='infoflow_direction',
            field=models.CharField(choices=[('TO_PROVIDER', 'To Provider'), ('FROM_PROVIDER', 'From Provider'), ('BOTH_DIRECTIONS', 'Both Directions')], default='BOTH_DIRECTIONS', max_length=20),
        ),
    ]
