# Generated by Django 3.2.10 on 2022-01-17 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0004_auto_20220117_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='production_start_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
