# Generated by Django 3.2.10 on 2021-12-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0006_alter_interface_interface_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_id',
            field=models.CharField(default='', max_length=10, verbose_name='Interface ID'),
        ),
    ]
