# Generated by Django 3.2.10 on 2021-12-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0008_alter_interface_is_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='accessibility',
            field=models.CharField(choices=[('DOMAIN_INTERNAL', 'Domain internal'), ('CROSS_DOMAIN', 'Cross domain')], default='DOMAIN_INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='interface',
            name='communication_pattern',
            field=models.CharField(choices=[('REQUEST_REPLY', 'Request-Reply'), ('FIRE_FORGET', 'Fire-Forget')], default='REQUEST_REPLY', max_length=20),
        ),
        migrations.AddField(
            model_name='interface',
            name='contract_description',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Interface Contract URL'),
        ),
        migrations.AddField(
            model_name='interface',
            name='is_multi_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='decommissioning_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
