# Generated by Django 3.2.10 on 2022-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0009_alter_interface_business_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='accessibility',
            field=models.CharField(choices=[('DOMAIN_INTERNAL', 'Domain internal'), ('CROSS_DOMAIN', 'Cross domain')], default='DOMAIN_INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='business_domain',
            field=models.CharField(choices=[('A.1 ACME Core', '-A.1 ACME Core'), ('A.2 ACME Partner', '- A.2 ACME Partner'), ('A.2.1 ACME Partner Address', '-- A.2.1 ACME Partner Address'), ('A.2.3 ACME Partner Contact', '-- A.2.3 ACME Partner Contact'), ('B.1 ACME Contract', '- B.1 ACME Contract'), ('B.2 ACME Offer', '- B.2 ACME Offer'), ('B.2.1 ACME Offer Company', '-- B.2.1 ACME Offer Company'), ('C.1 ACME Finance', '- C.1 ACME Finance'), ('C.2 ACME Legal & Compliance', '- C.2 ACME Legal & Compliance'), ('C.2.1 ACME Legal', '-- C.2.1 ACME Legal'), ('C.2.2 ACME Compliance', '-- C.2 ACME Compliance'), ('D.1 ACME Purchasing', '- D.1 ACME Purchasing')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='interface',
            name='communication_pattern',
            field=models.CharField(choices=[('REQUEST_REPLY', 'Request-Reply'), ('FIRE_FORGET', 'Fire-Forget')], default='REQUEST_REPLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='info_classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIONAL', 'Confidentional'), ('SECRET', 'Secret')], default='INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='infoflow_direction',
            field=models.CharField(choices=[('TO_PROVIDER', 'To Provider'), ('FROM_PROVIDER', 'From Provider'), ('BOTH_DIRECTIONS', 'Both Directions')], default='BOTH_DIRECTIONS', max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='model_origin',
            field=models.CharField(choices=[('CODE', 'Code'), ('CONTRACT', 'Contract'), ('MODEL', 'Model')], default='CODE', max_length=10),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('EINGANG', 'Eingang'), ('ENTWICKLUNG', 'Entwicklung'), ('TEST', 'Test'), ('PRODUKTION', 'Produktion'), ('RUECKZUG', 'Rueckzug'), ('HISTORISCH', 'Historisch'), ('ABGELEHNT', 'Abgelehnt')], default='EINGANG', max_length=32),
        ),
    ]
