# Generated by Django 3.2.10 on 2021-12-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0009_auto_20211228_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='is_multi_provider',
            new_name='multi_provider',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='is_owned',
            new_name='owned_interface',
        ),
    ]
