# Generated by Django 3.2.10 on 2021-12-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0010_auto_20211228_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='restriction_code',
            field=models.CharField(blank=True, choices=[('NUTZUNG', 'Nutzung'), ('TEST', 'Test')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='restriction_text',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
