# Generated by Django 3.2.10 on 2021-12-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0011_auto_20211228_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default='', max_length=10, verbose_name='APP-ID')),
                ('short_name', models.CharField(default='', max_length=20)),
                ('mail_address', models.EmailField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceImplentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_basepath', models.CharField(default='', max_length=100)),
                ('implementation_counter', models.PositiveIntegerField(default=1)),
                ('implementation_type', models.CharField(choices=[('WEB_SERVICE', 'Web Service'), ('API', 'Api'), ('QUEUE', 'Queue')], default='API', max_length=20)),
                ('interface', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_interface.interface')),
                ('provider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app_interface.application')),
            ],
        ),
    ]
