# Generated by Django 3.2.10 on 2021-12-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0012_application_interfaceimplentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceimplentation',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='interfaceimplentation',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='InterfaceImplentation',
        ),
    ]
