# Generated by Django 3.2.10 on 2022-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0012_auto_20220119_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='accessibility',
            field=models.CharField(choices=[('', '---------'), ('DOMAIN_INTERNAL', 'Domain internal'), ('CROSS_DOMAIN', 'Cross domain')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='communication_pattern',
            field=models.CharField(choices=[('', '---------'), ('REQUEST_REPLY', 'Request-Reply'), ('FIRE_FORGET', 'Fire-Forget')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='info_classification',
            field=models.CharField(choices=[('', '---------'), ('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIONAL', 'Confidentional'), ('SECRET', 'Secret')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='infoflow_direction',
            field=models.CharField(choices=[('', '---------'), ('TO_PROVIDER', 'To Provider'), ('FROM_PROVIDER', 'From Provider'), ('BOTH_DIRECTIONS', 'Both Directions')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='interface',
            name='model_origin',
            field=models.CharField(choices=[('', '---------'), ('CODE', 'Code'), ('CONTRACT', 'Contract'), ('MODEL', 'Model')], default=None, max_length=10),
        ),
    ]
