# Generated by Django 3.2.10 on 2022-01-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
        ('app_interface', '0013_auto_20211231_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='owner_application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app_application.application'),
        ),
    ]
