# Generated by Django 3.2.10 on 2022-01-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0014_alter_interface_business_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='restriction_text',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
