# Generated by Django 3.2.10 on 2022-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0015_alter_interface_restriction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('EINGANG', 'Eingang'), ('ENTWICKLUNG', 'Entwicklung'), ('TEST', 'Test'), ('PRODUKTION', 'Produktion'), ('RUECKZUG', 'Rueckzug'), ('HISTORISCH', 'Historisch'), ('ABGELEHNT', 'Abgelehnt')], default='EINGANG', max_length=32),
        ),
    ]
