# Generated by Django 3.2.10 on 2022-01-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0015_alter_interface_restriction_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='model_origin',
            new_name='interface_origin',
        ),
    ]
