# Generated by Django 3.2.10 on 2022-05-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0016_rename_model_origin_interface_interface_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='contract_description',
            new_name='doc_link',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='business_domain',
            new_name='domain_name',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='version',
            new_name='major_version',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='decommissioning_at',
            new_name='workend_date',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='communication_pattern',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='interface_origin',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='interface_type',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='multi_provider',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='production_start_at',
        ),
    ]
