# Generated by Django 3.2.13 on 2022-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0017_auto_20220505_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='doc_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Doc Link'),
        ),
    ]
