# Generated by Django 3.2.10 on 2022-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_implementation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='implementation_type',
            field=models.CharField(choices=[('WEB_SERVICE', 'Web Service'), ('API', 'API'), ('QUEUE', 'Queue')], default='API', max_length=20),
        ),
    ]
