# Generated by Django 3.2.10 on 2022-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_implementation', '0002_alter_implementation_implementation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='implementation_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
