# Generated by Django 3.2.10 on 2022-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_implementation', '0002_alter_implementation_implementation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='implementation_type',
            field=models.CharField(choices=[('API', 'API'), ('WEB_SERVICE', 'SOAP Web Service'), ('QUEUE', 'Queue'), ('FILE_TRANSFER', 'File Transfer')], default='API', max_length=20),
        ),
    ]
