# Generated by Django 3.2.10 on 2022-01-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
        ('app_implementation', '0003_alter_implementation_implementation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='consumers',
            field=models.ManyToManyField(blank=True, related_name='consumers', to='app_application.Application'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider', to='app_application.application'),
        ),
    ]
