# Generated by Django 3.2.10 on 2022-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_implementation', '0004_auto_20220118_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='implementation_counter',
            field=models.CharField(default='wird vom Tool vergeben', max_length=3),
        ),
    ]
