# Generated by Django 3.2.10 on 2022-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_implementation', '0005_alter_implementation_implementation_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='implementation_counter',
            field=models.CharField(default='wird vom Tool vergeben', max_length=23),
        ),
    ]
